


CREATE TYPE USER_ROLE AS ENUM('USER','CONSULTANT','DERMATOLOGIST','ADMIN');
CREATE TYPE PROVIDER_TYPE AS ENUM('LOCAL','GOOGLE');

CREATE TABLE USERS(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(200) UNIQUE NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	ROLE USER_ROLE NOT NULL,
	PROVIDER PROVIDER_TYPE DEFAULT 'LOCAL',
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USERS(NAME,EMAIL,PASSWORD,ROLE) VALUES('ALEXA','admin@example.com','$argon2id$v=19$m=65536,t=3,p=4$pdR6TwmBEIKwVoqx9n4vBQ$YTDcWlhupmJfFyL5J0/tbPe1n+0sPv4mZwjIvwHTnU4','ADMIN')

ALTER TABLE USERS ADD COLUMN IF NOT EXISTS STATUS VARCHAR(20) DEFAULT 'PENDING';
UPDATE USERS SET STATUS = 'APPROVED' WHERE ROLE IN ('ADMIN', 'USER');
SELECT * FROM USERS


CREATE TABLE SKIN_PROFILES (
    ID SERIAL PRIMARY KEY,
    USER_ID INT UNIQUE REFERENCES USERS(ID) ON DELETE CASCADE,
    SKIN_TYPE VARCHAR(50),
    AGE_GROUP VARCHAR(20),
    WATER_INTAKE NUMERIC(3, 1),
    SLEEP_QUALITY VARCHAR(50),
    ENVIRONMENT VARCHAR(100),
    ALLERGIES VARCHAR(255),
    SENSITIVITIES VARCHAR(255),
    CONCERNS TEXT[],
    SCORE INT DEFAULT 100,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM SKIN_PROFILES

CREATE TABLE SKINASSESSMENT (
	ID SERIAL PRIMARY KEY,
	USER_ID INT REFERENCES USERS(ID) ON DELETE CASCADE,
	ASSESSMENT_DATE DATE DEFAULT CURRENT_DATE,
	SKIN_HEALTH_SCORE INT,
	OVERALL_CONDITION VARCHAR(200),
	NOTES TEXT,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE SKINCONCERN(
	ID SERIAL PRIMARY KEY,
	ASSESSMENT_ID INT REFERENCES SKINASSESSMENT(ID) ON DELETE CASCADE,
	CONCERN_NAME VARCHAR(100),
	SEVERITY VARCHAR(100),
	PRIORITY INT
);


CREATE TABLE RISKFACTOR(
	ID SERIAL PRIMARY KEY,
	ASSESSMENT_ID INT REFERENCES SKINASSESSMENT(ID) ON DELETE CASCADE,
	RISK_NAME VARCHAR(100),
	DESCRIPTION TEXT,
	RISK_LEVEL VARCHAR(50)
);
