-- Enable UUID extension for ingredient intelligence
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create ENUM types
DO $$ BEGIN
    CREATE TYPE USER_ROLE AS ENUM('USER', 'CONSULTANT', 'DERMATOLOGIST', 'ADMIN');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE PROVIDER_TYPE AS ENUM('LOCAL', 'GOOGLE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 1. USERS
CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE USER_ROLE NOT NULL,
    PROVIDER PROVIDER_TYPE DEFAULT 'LOCAL',
    STATUS VARCHAR(20) DEFAULT 'PENDING', -- Secure default fallback
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM USERS;

-- Trigger for role-based status assignment
CREATE OR REPLACE FUNCTION auto_assign_user_status()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.ROLE IN ('CONSULTANT', 'DERMATOLOGIST') THEN
        NEW.STATUS := 'PENDING';
    ELSE
        NEW.STATUS := 'APPROVED';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_assign_user_status
BEFORE INSERT ON USERS
FOR EACH ROW
EXECUTE FUNCTION auto_assign_user_status();

-- Seed initial Admin User
INSERT INTO USERS (NAME, EMAIL, PASSWORD, ROLE, STATUS) 
VALUES ('ALEXA', 'admin@example.com', '$argon2id$v=19$m=65536,t=3,p=4$pdR6TwmBEIKwVoqx9n4vBQ$YTDcWlhupmJfFyL5J0/tbPe1n+0sPv4mZwjIvwHTnU4', 'ADMIN', 'APPROVED')
ON CONFLICT (EMAIL) DO NOTHING;

-- 2. SKIN_PROFILES
CREATE TABLE SKIN_PROFILES (
    ID SERIAL PRIMARY KEY,
    USER_ID INT UNIQUE REFERENCES USERS(ID) ON DELETE CASCADE,
    SKIN_TYPE VARCHAR(50),
    AGE_GROUP VARCHAR(20),
    WATER_INTAKE NUMERIC(3, 1),
    SLEEP_QUALITY VARCHAR(50),
    ENVIRONMENT VARCHAR(100),
    ALLERGIES VARCHAR(255),
    SENSITIVITIES VARCHAR(255),
    CONCERNS TEXT[],
    SCORE INT DEFAULT 100,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM SKIN_PROFILES;

-- 3. SKINASSESSMENT
CREATE TABLE SKINASSESSMENT (
    ID SERIAL PRIMARY KEY,
    USER_ID INT REFERENCES USERS(ID) ON DELETE CASCADE,
    ASSESSMENT_DATE DATE DEFAULT CURRENT_DATE,
    SKIN_HEALTH_SCORE INT,
    OVERALL_CONDITION VARCHAR(200),
    NOTES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM SKINASSESSMENT;

-- 4. SKINCONCERN & RISKFACTOR
CREATE TABLE SKINCONCERN (
    ID SERIAL PRIMARY KEY,
    ASSESSMENT_ID INT REFERENCES SKINASSESSMENT(ID) ON DELETE CASCADE,
    CONCERN_NAME VARCHAR(100),
    SEVERITY VARCHAR(100),
    PRIORITY INT
);
SELECT * FROM SKINCONCERN;

CREATE TABLE RISKFACTOR (
    ID SERIAL PRIMARY KEY,
    ASSESSMENT_ID INT REFERENCES SKINASSESSMENT(ID) ON DELETE CASCADE,
    RISK_NAME VARCHAR(100),
    DESCRIPTION TEXT,
    RISK_LEVEL VARCHAR(50)
);
SELECT * FROM RISKFACTOR;

-- 5. ROUTINES & ROUTINE_STEPS
CREATE TABLE ROUTINES (
    ID SERIAL PRIMARY KEY,
    USER_ID INT REFERENCES USERS(ID) ON DELETE CASCADE,
    PATIENT_NAME VARCHAR(100),
    SEASONAL_NOTE VARCHAR(255),
    ADAPTATION_SUMMARY TEXT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    HAS_DERMATOLOGIST_OVERRIDE BOOLEAN DEFAULT FALSE,
    DERMATOLOGIST_NOTES TEXT,
    DERMATOLOGIST_STEPS JSONB,
    AUTHORIZED_BY_DERMA_ID INT REFERENCES USERS(ID) ON DELETE SET NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM ROUTINES;

CREATE TABLE ROUTINE_STEPS (
    ID SERIAL PRIMARY KEY,
    ROUTINE_ID INT REFERENCES ROUTINES(ID) ON DELETE CASCADE,
    TIMING VARCHAR(30) CHECK (TIMING IN ('Morning', 'Evening', 'Weekly', 'Clinical Step')),
    STEP_ORDER INT NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    PRODUCT_RECOMMENDATION VARCHAR(255),
    ACTIVE_INGREDIENT VARCHAR(255),
    INSTRUCTIONS TEXT,
    ADAPTATION_BADGE VARCHAR(100) DEFAULT 'Maintained'
);
SELECT * FROM ROUTINE_STEPS;

CREATE TABLE WEEKLY_TREATMENTS (
    ID SERIAL PRIMARY KEY,
    ROUTINE_ID INT REFERENCES ROUTINES(ID) ON DELETE CASCADE,
    DAY_OF_WEEK VARCHAR(15) NOT NULL,
    TREATMENT_TYPE VARCHAR(100) NOT NULL,
    INSTRUCTIONS TEXT,
    CATEGORY VARCHAR(50) DEFAULT '✨ Exfoliation',
    PRODUCT VARCHAR(255) DEFAULT 'Targeted Treatment Mask'
);
SELECT * FROM WEEKLY_TREATMENTS;

CREATE TABLE USER_ROUTINE_FEEDBACK (
    ID SERIAL PRIMARY KEY,
    USER_ID INT REFERENCES USERS(ID) ON DELETE CASCADE,
    ROUTINE_ID INT REFERENCES ROUTINES(ID) ON DELETE CASCADE,
    IS_EFFECTIVE BOOLEAN DEFAULT TRUE,
    ALLERGIES_REPORTED TEXT,
    PRODUCTS_DISLIKED TEXT,
    USER_NOTES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM USER_ROUTINE_FEEDBACK;

CREATE TABLE PRESCRIPTIONS (
    ID SERIAL PRIMARY KEY,
    PATIENT_ID INT REFERENCES USERS(ID) ON DELETE CASCADE,
    DERMATOLOGIST_ID INT REFERENCES USERS(ID) ON DELETE SET NULL,
    ASSESSMENT_ID INT REFERENCES SKINASSESSMENT(ID) ON DELETE SET NULL,
    MEDICATION VARCHAR(255) NOT NULL,
    DOSAGE_DURATION VARCHAR(100) NOT NULL,
    INSTRUCTIONS TEXT,
    CONTRAINDICATION_OVERRIDE BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM PRESCRIPTIONS;

-- 6. APPOINTMENTS, LOGS & RECOMMENDATIONS
CREATE TABLE APPOINTMENTS (
    ID SERIAL PRIMARY KEY,
    PATIENT_ID INT REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSULTANT_ID INT REFERENCES USERS(ID) ON DELETE SET NULL,
    APPOINTMENT_DATE TIMESTAMP NOT NULL,
    PATIENT_NOTES TEXT,
    STATUS VARCHAR(50) DEFAULT 'Pending' CHECK (STATUS IN ('Pending', 'Approved', 'Rejected', 'Completed', 'Cancelled')),
    MEETING_LINK VARCHAR(255),
    CLINICAL_SUMMARY TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM APPOINTMENTS;

CREATE TABLE PROGRESS_LOGS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT REFERENCES USERS(ID) ON DELETE CASCADE,
    AM_COMPLETED BOOLEAN DEFAULT FALSE,
    PM_COMPLETED BOOLEAN DEFAULT FALSE,
    SKIN_FEELING_RATING INT DEFAULT 5,
    NOTES TEXT,
    LOG_DATE DATE DEFAULT CURRENT_DATE,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_user_daily_log UNIQUE (USER_ID, LOG_DATE) -- Rectified: Prevents duplicate daily entries
);
SELECT * FROM PROGRESS_LOGS;

CREATE TABLE CONSULTANT_RECOMMENDATIONS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT REFERENCES USERS(ID) ON DELETE CASCADE,
	CONSULTANT_ID INT REFERENCES USERS(ID) ON DELETE SET NULL,
    RECOMMENDATION_TEXT TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM CONSULTANT_RECOMMENDATIONS;

-- 7. INGREDIENT INTELLIGENCE
CREATE TABLE ingredients_master (
    ingredient_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    canonical_inci_name VARCHAR(255) NOT NULL UNIQUE,
    category VARCHAR(100) NOT NULL,
    comedogenic_rating INT CHECK (comedogenic_rating BETWEEN 0 AND 5),
    is_pregnancy_safe BOOLEAN DEFAULT TRUE,
    functions TEXT[] DEFAULT '{}',
    education_summary TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM ingredients_master;

CREATE TABLE ingredient_synonyms (
    synonym_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ingredient_id UUID NOT NULL REFERENCES ingredients_master(ingredient_id) ON DELETE CASCADE,
    synonym_name VARCHAR(255) UNIQUE NOT NULL
);
SELECT * FROM ingredient_synonyms;

CREATE TABLE ingredient_interactions (
    interaction_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ingredient_a_id UUID NOT NULL REFERENCES ingredients_master(ingredient_id) ON DELETE CASCADE,
    ingredient_b_id UUID NOT NULL REFERENCES ingredients_master(ingredient_id) ON DELETE CASCADE,
    interaction_type VARCHAR(50) NOT NULL,
    severity_level VARCHAR(50) NOT NULL,
    recommendation_text TEXT NOT NULL,
    CONSTRAINT unique_interaction_pair UNIQUE (ingredient_a_id, ingredient_b_id),
    CONSTRAINT prevent_self_interaction CHECK (ingredient_a_id <> ingredient_b_id) -- Rectified
);
SELECT * FROM ingredient_interactions;

-- PERFORMANCE & AI QUERY OPTIMIZATION INDEXES
CREATE INDEX idx_ingredients_inci ON ingredients_master(canonical_inci_name);
CREATE INDEX idx_synonyms_name ON ingredient_synonyms(synonym_name);

-- Added Indexes for AI Context Lookups
CREATE INDEX idx_routines_user_active ON ROUTINES(USER_ID, IS_ACTIVE);
CREATE INDEX idx_appointments_patient ON APPOINTMENTS(PATIENT_ID);
CREATE INDEX idx_appointments_consultant ON APPOINTMENTS(CONSULTANT_ID);
CREATE INDEX idx_skinassessment_user ON SKINASSESSMENT(USER_ID);
CREATE INDEX idx_progress_logs_user_date ON PROGRESS_LOGS(USER_ID, LOG_DATE);
