# Stage 1: Serve HTML/CSS/JS with Nginx
FROM nginx:alpine

# Copy static assets
COPY index.html /usr/share/nginx/html/index.html
COPY css /usr/share/nginx/html/css
COPY js /usr/share/nginx/html/js
COPY images /usr/share/nginx/html/images
COPY pages /usr/share/nginx/html/pages

# Copy Nginx Configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
