"""create phase 3 routine and ingredient tables

Revision ID: 5023b610c1b6
Revises: a3c5e462267a
Create Date: 2026-08-01 23:21:30.230669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5023b610c1b6'
down_revision: Union[str, Sequence[str], None] = 'a3c5e462267a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('benefits', sa.JSON(), nullable=False),
    sa.Column('side_effects', sa.JSON(), nullable=False),
    sa.Column('suitable_skin_types', sa.JSON(), nullable=False),
    sa.Column('suitable_skin_concerns', sa.JSON(), nullable=False),
    sa.Column('usage_time', sa.String(length=50), nullable=False),
    sa.Column('compatible_ingredients', sa.JSON(), nullable=False),
    sa.Column('conflicting_ingredients', sa.JSON(), nullable=False),
    sa.Column('safety_warnings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)
    op.create_table('ingredient_compatibility_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('selected_ingredients', sa.JSON(), nullable=False),
    sa.Column('is_safe', sa.Integer(), nullable=False),
    sa.Column('conflicts_found', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_compatibility_checks_id'), 'ingredient_compatibility_checks', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_compatibility_checks_user_id'), 'ingredient_compatibility_checks', ['user_id'], unique=False)
    op.create_table('skincare_routines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('routine_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skincare_routines_id'), 'skincare_routines', ['id'], unique=False)
    op.create_index(op.f('ix_skincare_routines_routine_type'), 'skincare_routines', ['routine_type'], unique=False)
    op.create_index(op.f('ix_skincare_routines_user_id'), 'skincare_routines', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skincare_routines_user_id'), table_name='skincare_routines')
    op.drop_index(op.f('ix_skincare_routines_routine_type'), table_name='skincare_routines')
    op.drop_index(op.f('ix_skincare_routines_id'), table_name='skincare_routines')
    op.drop_table('skincare_routines')
    op.drop_index(op.f('ix_ingredient_compatibility_checks_user_id'), table_name='ingredient_compatibility_checks')
    op.drop_index(op.f('ix_ingredient_compatibility_checks_id'), table_name='ingredient_compatibility_checks')
    op.drop_table('ingredient_compatibility_checks')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
