"""create_phase_6_tables

Revision ID: 89ad7e3554e5
Revises: b8a7109c6d1f
Create Date: 2026-08-02 10:14:53.334868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ad7e3554e5'
down_revision: Union[str, Sequence[str], None] = 'b8a7109c6d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('consultant_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('treatment_recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_consultant_id'), 'consultations', ['consultant_id'], unique=False)
    op.create_index(op.f('ix_consultations_id'), 'consultations', ['id'], unique=False)
    op.create_index(op.f('ix_consultations_patient_id'), 'consultations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_consultations_scheduled_at'), 'consultations', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_consultations_status'), 'consultations', ['status'], unique=False)
    op.create_table('clinical_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('custom_routine', sa.JSON(), nullable=True),
    sa.Column('recommended_products', sa.JSON(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['product_recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_reviews_id'), 'clinical_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_clinical_reviews_patient_id'), 'clinical_reviews', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_reviews_reviewer_id'), 'clinical_reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_reviews_reviewer_id'), table_name='clinical_reviews')
    op.drop_index(op.f('ix_clinical_reviews_patient_id'), table_name='clinical_reviews')
    op.drop_index(op.f('ix_clinical_reviews_id'), table_name='clinical_reviews')
    op.drop_table('clinical_reviews')
    op.drop_index(op.f('ix_consultations_status'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_scheduled_at'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_patient_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_consultant_id'), table_name='consultations')
    op.drop_table('consultations')
    # ### end Alembic commands ###
