/*
# Module 4 & Module 5 — Skin Intelligence, Personalized Skincare, and Ingredient Intelligence

## Overview
This migration adds the database tables required for:
- Module 4: Personalized routines (morning/evening/weekly/seasonal), adaptive routine updates, user feedback on routines, and product recommendations.
- Module 5: Ingredient library, personalized ingredient suitability, ingredient interaction analysis, and allergy detection.

## New Tables

1. `routines` — Stores AI-generated personalized skincare routines for a user. Each routine is linked to an assessment and contains structured JSON for morning, evening, weekly, and seasonal plans. Tracks whether the routine was generated by Gemini AI or the rule-based fallback.
2. `routine_feedback` — Stores user feedback after following a routine. Includes improvement status, side effects (irritation, redness, dryness, burning, breakouts), ingredient-specific feedback, and free-text notes. Used to influence future routine generation.
3. `adaptive_updates` — Stores the comparison between a previous and latest assessment, including score trend, concern changes, and Gemini-generated routine adjustments.
4. `products` — Product catalog for recommendations. Stores product name, brand, category, key ingredients, purchase link, and suitability metadata.
5. `product_recommendations` — Links products to assessments with personalized reasoning and allergy/suitability check results.
6. `ingredients` — Ingredient library with structured metadata: category, description, benefits, suitable skin types, common concerns, cautions, interactions, and educational content.
7. `ingredient_interactions` — Known interaction rules between ingredient pairs: risk level, description, and scheduling recommendations.
8. `ingredient_analyses` — Stores personalized ingredient suitability analyses for a user, generated by Gemini or the deterministic fallback. Includes suitability score, reasoning, benefits, cautions, and recommended usage.

## Modified Tables

### user_profiles (extended)
Added columns for:
- `allergies` (text) — Known allergies (e.g., fragrance, nuts, latex)
- `skincare_goals` (text) — User's skincare goals (e.g., anti-aging, acne control)
- `current_products` (text) — Current skincare products being used
- `previous_ingredient_issues` (text) — Ingredients that previously caused issues

## Security (RLS)
- All new tables have RLS enabled.
- Owner-scoped CRUD for user data (routines, feedback, adaptive updates, ingredient analyses, product recommendations).
- Staff (consultant, dermatologist, admin) can read user data for dashboard synchronization.
- Ingredients, ingredient_interactions, and products are readable by all authenticated users (shared reference data).
- Only authenticated users can insert/update their own data.

## Important Notes
1. `user_id` columns on owner-scoped tables default to `auth.uid()` so inserts that omit `user_id` still satisfy RLS.
2. All new tables use `gen_random_uuid()` for primary keys.
3. Indexes added for frequently-queried columns (user_id, assessment_id, routine_id).
4. Existing data is never modified or deleted — only new columns and tables are added.
*/

-- ============ EXTEND USER_PROFILES TABLE ============
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS allergies text;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS skincare_goals text;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS current_products text;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS previous_ingredient_issues text;

-- ============ ROUTINES TABLE ============
CREATE TABLE IF NOT EXISTS routines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  assessment_id uuid REFERENCES skin_assessments(id) ON DELETE SET NULL,
  morning_routine jsonb,
  evening_routine jsonb,
  weekly_plan jsonb,
  seasonal_recommendations jsonb,
  source text NOT NULL DEFAULT 'rule_based' CHECK (source IN ('gemini', 'rule_based')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE routines ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_routines_user_id ON routines(user_id);
CREATE INDEX IF NOT EXISTS idx_routines_assessment_id ON routines(assessment_id);

DROP POLICY IF EXISTS "select_own_or_staff_routines" ON routines;
CREATE POLICY "select_own_or_staff_routines" ON routines FOR SELECT
  TO authenticated USING (
    auth.uid() = user_id OR EXISTS (
      SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('consultant', 'dermatologist', 'admin')
    )
  );

DROP POLICY IF EXISTS "insert_own_routines" ON routines;
CREATE POLICY "insert_own_routines" ON routines FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_routines" ON routines;
CREATE POLICY "update_own_routines" ON routines FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_routines" ON routines;
CREATE POLICY "delete_own_routines" ON routines FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ============ ROUTINE_FEEDBACK TABLE ============
CREATE TABLE IF NOT EXISTS routine_feedback (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  routine_id uuid REFERENCES routines(id) ON DELETE CASCADE,
  assessment_id uuid REFERENCES skin_assessments(id) ON DELETE SET NULL,
  improvement_status text CHECK (improvement_status IN ('improved', 'no_change', 'worsened')),
  experienced_irritation boolean DEFAULT false,
  experienced_redness boolean DEFAULT false,
  experienced_dryness boolean DEFAULT false,
  experienced_burning boolean DEFAULT false,
  experienced_breakouts boolean DEFAULT false,
  ingredient_feedback text,
  notes text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE routine_feedback ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_feedback_user_id ON routine_feedback(user_id);
CREATE INDEX IF NOT EXISTS idx_feedback_routine_id ON routine_feedback(routine_id);

DROP POLICY IF EXISTS "select_own_or_staff_feedback" ON routine_feedback;
CREATE POLICY "select_own_or_staff_feedback" ON routine_feedback FOR SELECT
  TO authenticated USING (
    auth.uid() = user_id OR EXISTS (
      SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('consultant', 'dermatologist', 'admin')
    )
  );

DROP POLICY IF EXISTS "insert_own_feedback" ON routine_feedback;
CREATE POLICY "insert_own_feedback" ON routine_feedback FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_feedback" ON routine_feedback;
CREATE POLICY "update_own_feedback" ON routine_feedback FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_feedback" ON routine_feedback;
CREATE POLICY "delete_own_feedback" ON routine_feedback FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ============ ADAPTIVE_UPDATES TABLE ============
CREATE TABLE IF NOT EXISTS adaptive_updates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  previous_assessment_id uuid REFERENCES skin_assessments(id) ON DELETE SET NULL,
  latest_assessment_id uuid REFERENCES skin_assessments(id) ON DELETE SET NULL,
  previous_score integer,
  latest_score integer,
  score_trend text CHECK (score_trend IN ('improved', 'declined', 'stable')),
  concern_changes jsonb,
  routine_adjustments jsonb,
  overall_progress text,
  source text NOT NULL DEFAULT 'rule_based' CHECK (source IN ('gemini', 'rule_based')),
  created_at timestamptz DEFAULT now()
);

ALTER TABLE adaptive_updates ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_adaptive_user_id ON adaptive_updates(user_id);

DROP POLICY IF EXISTS "select_own_or_staff_adaptive" ON adaptive_updates;
CREATE POLICY "select_own_or_staff_adaptive" ON adaptive_updates FOR SELECT
  TO authenticated USING (
    auth.uid() = user_id OR EXISTS (
      SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('consultant', 'dermatologist', 'admin')
    )
  );

DROP POLICY IF EXISTS "insert_own_adaptive" ON adaptive_updates;
CREATE POLICY "insert_own_adaptive" ON adaptive_updates FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_adaptive" ON adaptive_updates;
CREATE POLICY "delete_own_adaptive" ON adaptive_updates FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ============ PRODUCTS TABLE ============
CREATE TABLE IF NOT EXISTS products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  brand text,
  category text NOT NULL,
  key_ingredients text[],
  description text,
  purchase_link text,
  suitable_skin_types text[],
  suitable_concerns text[],
  price_range text,
  popularity integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);

DROP POLICY IF EXISTS "select_all_products" ON products;
CREATE POLICY "select_all_products" ON products FOR SELECT
  TO authenticated USING (true);

-- ============ PRODUCT_RECOMMENDATIONS TABLE ============
CREATE TABLE IF NOT EXISTS product_recommendations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  assessment_id uuid REFERENCES skin_assessments(id) ON DELETE CASCADE,
  product_id uuid REFERENCES products(id) ON DELETE SET NULL,
  product_name text,
  product_brand text,
  product_category text,
  key_ingredients text[],
  reasoning text,
  allergy_conflict boolean DEFAULT false,
  allergy_conflict_details text,
  suitability_score integer,
  is_popular_pick boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE product_recommendations ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_prodrecs_user_id ON product_recommendations(user_id);
CREATE INDEX IF NOT EXISTS idx_prodrecs_assessment_id ON product_recommendations(assessment_id);

DROP POLICY IF EXISTS "select_own_or_staff_prodrecs" ON product_recommendations;
CREATE POLICY "select_own_or_staff_prodrecs" ON product_recommendations FOR SELECT
  TO authenticated USING (
    auth.uid() = user_id OR EXISTS (
      SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('consultant', 'dermatologist', 'admin')
    )
  );

DROP POLICY IF EXISTS "insert_own_prodrecs" ON product_recommendations;
CREATE POLICY "insert_own_prodrecs" ON product_recommendations FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_prodrecs" ON product_recommendations;
CREATE POLICY "delete_own_prodrecs" ON product_recommendations FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ============ INGREDIENTS TABLE ============
CREATE TABLE IF NOT EXISTS ingredients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  category text NOT NULL,
  description text,
  benefits text[],
  suitable_skin_types text[],
  common_concerns text[],
  cautions text[],
  common_interactions text[],
  education text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE ingredients ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_ingredients_category ON ingredients(category);
CREATE INDEX IF NOT EXISTS idx_ingredients_name ON ingredients(name);

DROP POLICY IF EXISTS "select_all_ingredients" ON ingredients;
CREATE POLICY "select_all_ingredients" ON ingredients FOR SELECT
  TO authenticated USING (true);

-- ============ INGREDIENT_INTERACTIONS TABLE ============
CREATE TABLE IF NOT EXISTS ingredient_interactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ingredient_a text NOT NULL,
  ingredient_b text NOT NULL,
  risk_level text NOT NULL CHECK (risk_level IN ('low', 'moderate', 'high')),
  description text,
  recommended_schedule text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE ingredient_interactions ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_interactions_a ON ingredient_interactions(ingredient_a);
CREATE INDEX IF NOT EXISTS idx_interactions_b ON ingredient_interactions(ingredient_b);

DROP POLICY IF EXISTS "select_all_interactions" ON ingredient_interactions;
CREATE POLICY "select_all_interactions" ON ingredient_interactions FOR SELECT
  TO authenticated USING (true);

-- ============ INGREDIENT_ANALYSES TABLE ============
CREATE TABLE IF NOT EXISTS ingredient_analyses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  ingredient_name text NOT NULL,
  suitability text CHECK (suitability IN ('excellent_match', 'good_match', 'use_with_caution', 'not_recommended')),
  score integer,
  reason text,
  benefits_for_user text[],
  cautions_for_user text[],
  recommended_usage text,
  alternative_ingredients text[],
  allergy_conflict boolean DEFAULT false,
  allergy_conflict_details text,
  source text NOT NULL DEFAULT 'rule_based' CHECK (source IN ('gemini', 'rule_based')),
  created_at timestamptz DEFAULT now()
);

ALTER TABLE ingredient_analyses ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_analyses_user_id ON ingredient_analyses(user_id);
CREATE INDEX IF NOT EXISTS idx_analyses_ingredient ON ingredient_analyses(ingredient_name);

DROP POLICY IF EXISTS "select_own_or_staff_analyses" ON ingredient_analyses;
CREATE POLICY "select_own_or_staff_analyses" ON ingredient_analyses FOR SELECT
  TO authenticated USING (
    auth.uid() = user_id OR EXISTS (
      SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('consultant', 'dermatologist', 'admin')
    )
  );

DROP POLICY IF EXISTS "insert_own_analyses" ON ingredient_analyses;
CREATE POLICY "insert_own_analyses" ON ingredient_analyses FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_analyses" ON ingredient_analyses;
CREATE POLICY "delete_own_analyses" ON ingredient_analyses FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ============ TRIGGERS: update updated_at for new tables ============
DROP TRIGGER IF EXISTS routines_updated_at ON routines;
CREATE TRIGGER routines_updated_at BEFORE UPDATE ON routines
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();