/*
# Module 9/10 — Recommendation Management + Notification System

## Overview
Two independent additions requested by the dashboard-completion task:

1. Extends the existing `recommendations` table (created in the original
   schema migration) so Consultant/Dermatologist staff can actually create,
   update, and delete recommendations for any user's assessment — not just
   read them. Previously only SELECT had a staff-inclusive policy; INSERT
   and DELETE were owner-only and there was no UPDATE policy at all, which
   is why "Recommendation Management" was structurally impossible for
   staff regardless of what the UI did.

2. Adds a real (not fake) in-app notification system: `notifications` for
   individual notification rows with read/unread state, and
   `notification_preferences` for per-user reminder settings (hydration,
   sleep, routine). Notifications are generated by the client when a user
   opens the app and a real condition is met (see frontend/js/notifications.js)
   — there is no scheduled/background job in this environment, so this is
   an honest "checked on load" implementation rather than OS-level push.

## Changes to `recommendations`
- Add `status` (active/reviewed/archived), `created_by`, `source`
  (system/consultant/dermatologist) so staff-authored recommendations are
  distinguishable from the Module 1-3 auto-generated ones and can carry a
  workflow state.
- Add UPDATE policy (staff only — system-generated recommendations aren't
  user-editable, and staff shouldn't edit each other's without a real
  reason, so this is intentionally staff-role-gated rather than row-owner).
- Extend INSERT policy to also allow staff for any assessment.
- Extend DELETE policy to also allow staff for any assessment.

## New Tables

1. `notifications` — one row per notification. `type` distinguishes
   routine_reminder / replenishment / hydration / sleep / progress_alert /
   platform. `metadata` carries a dedupe key (e.g. the date or assessment
   id) so the client doesn't spam duplicate notifications for the same
   trigger.

2. `notification_preferences` — one row per user, reminder toggles/times.

## Security (RLS)
- `recommendations`: see above.
- `notifications`: users manage only their own rows for read/update/delete.
  INSERT is allowed for the row owner OR staff/admin (so staff/admin can
  create a notification for a user, e.g. platform announcements), matching
  the access pattern already used elsewhere in this project.
- `notification_preferences`: owner-only, full CRUD.
*/

-- ============ RECOMMENDATIONS: STAFF MANAGEMENT ============
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'recommendations' AND column_name = 'status') THEN
    ALTER TABLE recommendations ADD COLUMN status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'reviewed', 'archived'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'recommendations' AND column_name = 'created_by') THEN
    ALTER TABLE recommendations ADD COLUMN created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'recommendations' AND column_name = 'source') THEN
    ALTER TABLE recommendations ADD COLUMN source text NOT NULL DEFAULT 'system' CHECK (source IN ('system', 'consultant', 'dermatologist'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'recommendations' AND column_name = 'updated_at') THEN
    ALTER TABLE recommendations ADD COLUMN updated_at timestamptz DEFAULT now();
  END IF;
END $$;

DROP POLICY IF EXISTS "insert_own_recs" ON recommendations;
CREATE POLICY "insert_own_or_staff_recs" ON recommendations FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM skin_assessments sa WHERE sa.id = recommendations.assessment_id AND sa.user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('consultant', 'dermatologist', 'admin'))
  );

DROP POLICY IF EXISTS "update_staff_recs" ON recommendations;
CREATE POLICY "update_staff_recs" ON recommendations FOR UPDATE
  TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('consultant', 'dermatologist', 'admin')))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('consultant', 'dermatologist', 'admin')));

DROP POLICY IF EXISTS "delete_own_recs" ON recommendations;
CREATE POLICY "delete_own_or_staff_recs" ON recommendations FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM skin_assessments sa WHERE sa.id = recommendations.assessment_id AND sa.user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('consultant', 'dermatologist', 'admin'))
  );

-- ============ NOTIFICATIONS ============
CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN ('routine_reminder', 'replenishment', 'hydration', 'sleep', 'progress_alert', 'platform')),
  title text NOT NULL,
  message text NOT NULL,
  is_read boolean NOT NULL DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications(user_id, is_read);

DROP POLICY IF EXISTS "select_own_notifications" ON notifications;
CREATE POLICY "select_own_notifications" ON notifications FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_or_staff_notifications" ON notifications;
CREATE POLICY "insert_own_or_staff_notifications" ON notifications FOR INSERT
  TO authenticated WITH CHECK (
    auth.uid() = user_id
    OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('consultant', 'dermatologist', 'admin'))
  );

DROP POLICY IF EXISTS "update_own_notifications" ON notifications;
CREATE POLICY "update_own_notifications" ON notifications FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_notifications" ON notifications;
CREATE POLICY "delete_own_notifications" ON notifications FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ============ NOTIFICATION PREFERENCES ============
CREATE TABLE IF NOT EXISTS notification_preferences (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  routine_reminder_enabled boolean NOT NULL DEFAULT true,
  hydration_reminder_enabled boolean NOT NULL DEFAULT false,
  hydration_reminder_time time DEFAULT '11:00',
  sleep_reminder_enabled boolean NOT NULL DEFAULT false,
  sleep_reminder_time time DEFAULT '21:30',
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "manage_own_notification_prefs" ON notification_preferences;
CREATE POLICY "manage_own_notification_prefs" ON notification_preferences FOR ALL
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
